name: test
on:
  workflow_dispatch:
jobs:

  jobB:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        run: | 
         echo"b"
  jobC:
    runs-on: ubuntu-22.04
    if: ${{ always() && (needs.jobB.result == 'success' || needs.jobB.result == 'failure') }}
    needs: [jobB]
    steps:
      - name: Checkout code
        run: |       
         echo "hello" 
